### ISSUE TITLE
Sometimes the shortened link takes me to a p*rn site.

### ISSUE THREAD

**Issue by jonesy-b-dev** [z1nc0r3/URL-Shortener-Plugin#5] opened 2024-03-11 08:36 UTC
I think it only happens when its the first time. I got a p\*rn site the first time I used a link from this plugin. 
I sended few of these links to my dad and he got a p\*rn site too....

Not really appropriate and I think you need to look for another link shortener service

**Comment by z1nc0r3** [comment] 2024-03-11 08:50
Hey Jonas,
I am sorry and apologize for the inappropriate response that you got from my plugin. I have checked plenty of URLs for accuracy but didn't find anything like this at the testing process.

I'll try to find the cause for this matter ASAP and if not possible I'll terminate the plugin from the store. For now, I think since the API is free, maybe cleanuri.com runs an advertisement process silently.

Thanks for submitting the issue and I'll make sure reliability of the plugin for future users. And if you can provide the URL you used for the shorter it will appreciated. But if that is not possible (privacy issues) that's fine.

**Comment by jonesy-b-dev** [comment] 2024-03-11 09:53
I highly suspect  the cleanuri being the problem. Maybe check on a new device or browser and see if it happens there. After I got it once i never got it again. I opened the link like 20 times and didnt got anything. Seems to only be the first time opening a link.

**Comment by jonesy-b-dev** [comment] 2024-03-11 10:00
Just tried on my phone, instantly got a sussy website. My phone browser warns me instantly for it.
Actually im getting only sussy websites now....

No idea if something is just wrong with my urls. Ill put them here.

Open on own risk I need to say now 😬
https://cleanuri.com/39gJAD
https://cleanuri.com/dADEJv
https://cleanuri.com/9XBnz1

**Comment by z1nc0r3** [comment] 2024-03-11 10:17
Thank you for the collaboration. I updated the plugin with tinyurl.com API. Hopefully, this will do the job. 

But again, this is not an officially documented API from tinyurl.com. Anyway, it is working at the moment but not sure for how long. Because they offer a paid API 🤷‍♂️

Please check the previous URLs on this update for the outputs. (It will take some time to populate the updated version on the store)

I'll close the issue for now. Please feel free to reopen if anything wrong.

**Closed as completed by z1nc0r3** 2024-03-11 10:17 UTC

**Comment by jonesy-b-dev** [comment] 2024-03-11 10:46
Amazing! I will try it out in a few hours.
